# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-api
  template:
    metadata:
      labels:
        app: spring-api
    spec:
      containers:
        - name: spring-api
          image: spring-api:latest
          ports:
            - containerPort: 8080
---
# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: spring-api-service
spec:
  type: NodePort
  selector:
    app: spring-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
